"""Storage contracts and the local SQLite personal-profile adapter."""

from .contracts import (
    ActiveSnapshotConflict,
    ApprovedEpisodicEventRepository,
    ApprovedEpisodicEventStorageFailure,
    CheckpointLifecycleEventRepository,
    CheckpointRepository,
    CheckpointSourceObservationRepository,
    CheckpointSourceObservationStorageFailure,
    EpisodicEventNotFound,
    InvalidKnowledgeDocumentScope,
    KnowledgeDocumentConflict,
    KnowledgeDocumentNotFound,
    KnowledgeDocumentRepository,
    KnowledgeDocumentSecretRejected,
    KnowledgeDocumentStorageFailure,
    KnowledgeDocumentSyncStoreResult,
    ManifestNodeNotFound,
    ManifestSnapshotNotFound,
    ProjectIndexRepository,
    ProjectProcedureRegistry,
    SourceStructureRepository,
)
from .reference import (
    ReferenceApprovedEpisodicEventRepository,
    ReferenceCheckpointLifecycleEventRepository,
    ReferenceCheckpointRepository,
    ReferenceCheckpointSourceObservationRepository,
    ReferenceKnowledgeDocumentRepository,
    ReferenceProjectIndexRepository,
    ReferenceSourceStructureRepository,
)
from .sqlite import (
    SQLiteCheckpointRepository,
    SQLiteKnowledgeDocumentRepository,
    SQLiteMigrationError,
    SQLiteSchemaTooNewError,
    SQLiteSourceStructureRepository,
)

__all__ = [
    "ActiveSnapshotConflict",
    "ApprovedEpisodicEventRepository",
    "ApprovedEpisodicEventStorageFailure",
    "CheckpointLifecycleEventRepository",
    "CheckpointRepository",
    "CheckpointSourceObservationRepository",
    "CheckpointSourceObservationStorageFailure",
    "EpisodicEventNotFound",
    "InvalidKnowledgeDocumentScope",
    "KnowledgeDocumentConflict",
    "KnowledgeDocumentNotFound",
    "KnowledgeDocumentRepository",
    "KnowledgeDocumentSecretRejected",
    "KnowledgeDocumentStorageFailure",
    "KnowledgeDocumentSyncStoreResult",
    "ManifestNodeNotFound",
    "ManifestSnapshotNotFound",
    "ProjectIndexRepository",
    "ProjectProcedureRegistry",
    "ReferenceApprovedEpisodicEventRepository",
    "ReferenceCheckpointLifecycleEventRepository",
    "ReferenceCheckpointRepository",
    "ReferenceCheckpointSourceObservationRepository",
    "ReferenceKnowledgeDocumentRepository",
    "ReferenceProjectIndexRepository",
    "ReferenceSourceStructureRepository",
    "SQLiteCheckpointRepository",
    "SQLiteKnowledgeDocumentRepository",
    "SQLiteMigrationError",
    "SQLiteSchemaTooNewError",
    "SQLiteSourceStructureRepository",
    "SourceStructureRepository",
]
